language: ruby

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1

cache: bundler

gemfile: gems.rb

bundler_args: --without benchmark development

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_success: ./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT
